language: python
python:
- '3.6'
cache: pip
install:
- pip install -r ./requirements.txt
script:
- bash test
env:
  global:
  - secure: bHWaB/KOP3VR55tEKOUr0EAfrKwFJ0nEq7UkHuuzQelbVLboUvxLrYKVAKHPHHLZgkZQAJhCNYyGBJQGAMKlLr4qMgJZ8XEj2RpBKqKsjZpA2ztUaz58umddR93zpxqDF2z9tPB55xC99Cf/eVq7eF7vR/ePV/c4HFIfR+VatEZudTaQwsF0seEuYNbiXLeVX09AYLshj1osNc7q4jfwFXoYSOVq2nRQnwidtwfCBq0Bq/X8M5VCju3odWyn/rsAuKejqG7TeAOaS/3mfe5IxApRhGjF3Ntvs0ANi/Qb8HZJ23P5R9gzUe2HIoKRGgW3Y1fvoOLdR2WyLuGY0h2sQbO2pqRn+V6lomIpUrerwcB4P6oywik9XzSZV/KSaWscIK68afyRp/yDYy4hTd+48OIi8n3aYnMIxjBSyq/SaH2WRoebknhBoo4G/DZYiozoWxHa8EWWH1e+UvD1SBqmGSbi075S5x3pW/IkiYI+z+OwMHuZnafMVw962zImd3VwB/BqT3eKXGAYEmW8pMR11MCvOgINExNzPBSGqsN4xKsKpyPYX1ZzVHtM0yNG6tKF4phLnMgo9XR/YvCTR0mqe1uzpzoc88p8/nxWafpQqf+jbyJ3oZtFLlzhIvvsu4KqEXjvjUAfSjFx1EY63dXWG/72rWOxPGvIEaqf/ZzaX8w=
  - secure: FPKdsoxi6zw6wwss5csAuqD+gJhnBau9x3bUIpKZg42YEyhUDa5f8FOqXTgmHYfSFFoNzvsJI6Nxi/+q7bFqITNA3S7hkfPOCkMeigqp3IrDpP65isd+iZ8aE4DjJmShMENrP3cgResmfDCMYHZW+ngPibAQ3Tby2j4r87Vk7V0MDDKZAwxhUEPPCw9YUi+aMuZ/fdYRnxxeAF/CVlR48ef0YhnlDuqgCZ1bwWBGUDDzUtex1zhe1JlAR2XhAEYe6jDte+pLEymXGVFqb4iK9YHMI125SVOU9R+YiXdsB/J3pij8aqUAHwf2z2wU0XTUi4o0Au078AyPV6ZLkFEtJW8bV2HAOS9eAFeeHDWauH0AV5BD752wXS8jeUloce+eb3p9aHd0yjkz0t6qdLDq98RSsMpfDRaaoeQ5TKm7cRqXhC1E2g3zDce03kfBE8XT61LX4KM6f2trG/ke5LB2QSxNa6MQSPJTbxh3z+zhuPeZ4RXrdRajo2D3svdjnuQEGieEZpOveK6lmLfC5FSMRuhSWY3/f8IlSfsoqOfJkx3O4zrm/8dpBSnv6l9CYhUvcW+EglinllEyEnxzFybkFqKqxEg0mRczS8j9M4QvAkAuerzCVWQWVDZe5wM3PJ5HeX9KEq7WIaPPokj0conHv9n7ieIJ3eEopMAxbxJsdYk=
